# Generated by Django 4.2.2 on 2023-06-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rensponse_provided_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userattempts',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempted_quiz', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='userattempts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='quiz.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='correct_answer', to='quiz.options'),
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.ManyToManyField(to='quiz.options'),
        ),
        migrations.AlterUniqueTogether(
            name='userattempts',
            unique_together={('user', 'quiz')},
        ),
    ]
