# Generated by Django 4.2.2 on 2023-06-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.AlterModelTable(
            name='studentquizattempt',
            table='student_quiz_attempt',
        ),
        migrations.AlterModelTable(
            name='studentquizresponses',
            table='student_quiz_repsonses',
        ),
    ]
