# Generated by Django 4.2.2 on 2023-06-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_instructor_alter_userattempts_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponses',
        ),
    ]
